import { ReactNode } from 'react'
import { globalFont } from '@/constants/data'
import '@/styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={globalFont.className}>{children}</body>
    </html>
  )
}
